Repository POS-CO2/2024_PGMS_FE, pull requests merged in 2024-10, with the labels that each got.

#165 [Refactor] 테이블 관련 멘토 피드백 반영
  react_frontend/src/SearchForms.js
  react_frontend/src/SiteLayout.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/TabsContainer.js
  react_frontend/src/actions/commonActions.js
  react_frontend/src/atoms/searchFormAtoms.js
  react_frontend/src/components/emperf/Ps_1_2.js
  react_frontend/src/components/emperf/Ps_1_2_Fp.js
  react_frontend/src/components/emperf/perflook/Psq.js
  react_frontend/src/components/emperf/perflook/Psq_Fp.js
  react_frontend/src/components/emperf/perflook/Tep.js
  react_frontend/src/components/fieldinfo/facility/Adm.js
  react_frontend/src/components/fieldinfo/facility/Fl.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/components/fieldinfo/project/detailSet/Esd.js
  react_frontend/src/components/fieldinfo/project/detailSet/Esd_Fp.js
  react_frontend/src/components/fieldinfo/project/detailSet/Rm.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Um.js
Labels: 버그, 프론트엔드, 기능생성

#166 [Feat] 예측 페이지 & 멘토 피드백 반영
  react_frontend/package-lock.json
  react_frontend/package.json
  react_frontend/src/App.js
  react_frontend/src/ChartCustom.js
  react_frontend/src/FormItem/DropDown.js
  react_frontend/src/FormItem/InputText.js
  react_frontend/src/FormItem/InputYear.js
  react_frontend/src/FormItem/SearchAtModal.js
  react_frontend/src/FormItem/SearchProjectModal.js
  react_frontend/src/FormItem/SelectCalendar.js
  react_frontend/src/SearchForms.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/css/chart.css
  react_frontend/src/assets/css/pds.css
  react_frontend/src/assets/css/searchForm.css
  react_frontend/src/assets/json/saDataEx.js
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/assets/json/tableColumn.js
  react_frontend/src/components/analfc/Ca.js
  react_frontend/src/components/analfc/Ea.js
  react_frontend/src/components/analfc/Eqf.js
  react_frontend/src/components/analfc/Sa.js
  react_frontend/src/components/emperf/Ps_1_2.js
  react_frontend/src/components/emperf/Ps_1_2_Fp.js
  react_frontend/src/components/emperf/perflook/Psq.js
  react_frontend/src/components/emperf/perflook/Psq_Fp.js
  react_frontend/src/components/emperf/perflook/Tep.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/components/fieldinfo/project/detailSet/Rm.js
Labels: 프론트엔드, 기능생성, 스타일

#167 [Fix] 수정사항 반영
  react_frontend/package-lock.json
  react_frontend/src/Chat.js
  react_frontend/src/Main.js
  react_frontend/src/Main_Admin.js
  react_frontend/src/Main_Hp.js
  react_frontend/src/SiteLayout.js
  react_frontend/src/chat/ChatList.js
  react_frontend/src/chat/Chatting.js
  react_frontend/src/chat/UserList.js
  react_frontend/src/components/login/Login.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Mal.js
  react_frontend/src/components/sysmng/Mm.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/modals/PdModal.js
  react_frontend/src/utils/AxiosInstance.js
Labels: 버그, 프론트엔드

#168 [Fix] 10/1 피드백 수정사항 반영
  react_frontend/src/App.js
  react_frontend/src/Chat.js
  react_frontend/src/Main.js
  react_frontend/src/Main_Hp.js
  react_frontend/src/assets/css/gridHp.css
  react_frontend/src/chat/Chatting.js
  react_frontend/src/components/sysmng/Mm.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/modals/PdModal.js
Labels: 버그, 프론트엔드, 스타일

#169 [Fix] warning 메세지 삭제
  react_frontend/src/FormItem/InputText.js
  react_frontend/src/FormItem/SelectCalendar.js
  react_frontend/src/Sidebar.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/components/fieldinfo/project/detailSet/Fd.js
  react_frontend/src/components/sysmng/Mm.js
  react_frontend/src/components/sysmng/Um.js
Labels: 버그

#170 [Feat] 예측 백엔드 연동 등
  react_frontend/src/FormItem/SelectCalendar.js
  react_frontend/src/assets/css/pdModal.css
  react_frontend/src/assets/json/saDataEx.js
  react_frontend/src/assets/json/tableColumn.js
  react_frontend/src/components/analfc/Ea.js
  react_frontend/src/components/analfc/Eqf.js
  react_frontend/src/components/analfc/Sa.js
  react_frontend/src/components/emperf/Ps_1_2.js
  react_frontend/src/components/emperf/Ps_1_2_Fp.js
  react_frontend/src/components/emperf/perflook/Psq.js
  react_frontend/src/components/emperf/perflook/Tep.js
  react_frontend/src/modals/PdModal.js
Labels: 버그, 프론트엔드, 기능생성, 스타일

#171 [HotFix] 메뉴접속 현황 버그 수정
  react_frontend/src/Chart.js
  react_frontend/src/Main_Admin.js
  react_frontend/src/Main_Hp.js
  react_frontend/src/components/emperf/perflook/Psq.js
  react_frontend/src/components/fieldinfo/project/detailSet/Pd.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Mal.js
  react_frontend/src/components/sysmng/Um.js
Labels: 버그, 프론트엔드

#172 [HotFix] 분석페이지 조회기간 막는 코드 추가
  react_frontend/src/FormItem/SelectCalendar.js
Labels: 버그, 프론트엔드

#173 [Fix] 예측 테이블 칼럼 순서 변경
  react_frontend/src/assets/json/tableColumn.js
Labels: 프론트엔드

#174 [Fix] 바 클릭 시 로딩페이지 없앰
  react_frontend/src/components/analfc/Sa.js
Labels: 프론트엔드

#175 [Fix] alert 메시지 html로 변경
  react_frontend/src/Main.js
  react_frontend/src/Main_Admin.js
  react_frontend/src/TableCustom.js
  react_frontend/src/actions/commonActions.js
  react_frontend/src/components/fieldinfo/facility/Adm.js
  react_frontend/src/components/fieldinfo/facility/Fl.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Mm.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드

#176 [Style] 세부사항 수정
  react_frontend/src/Chat.js
  react_frontend/src/Main_Hp.js
  react_frontend/src/Table.js
  react_frontend/src/assets/css/chat.css
Labels: 버그, 프론트엔드, 스타일

#177 [Hotfix] 본사담당자 스코프 전월대비 퍼센트 계산식 수정
  react_frontend/src/Main_Hp.js
Labels: 버그, 프론트엔드

#178 [Fix] 회의 수정사항 반영
  react_frontend/src/App.js
  react_frontend/src/ChartCustom.js
  react_frontend/src/Favorite.js
  react_frontend/src/FormItem/SearchProjectModal.js
  react_frontend/src/FormItem/SelectCalendar.js
  react_frontend/src/Main_Admin.js
  react_frontend/src/SearchForms.js
  react_frontend/src/SiteLayout.js
  react_frontend/src/Table.js
  react_frontend/src/TabsContainer.js
  react_frontend/src/assets/css/pjtModal.css
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/assets/json/tableColumn.js
  react_frontend/src/atoms/buttonAtoms.js
  react_frontend/src/atoms/pdsAtoms.js
  react_frontend/src/atoms/searchFormAtoms.js
  react_frontend/src/atoms/selectedRowAtoms.js
  react_frontend/src/atoms/tabAtoms.js
  react_frontend/src/components/analfc/Ca.js
  react_frontend/src/components/analfc/Ea.js
  react_frontend/src/components/analfc/Sa.js
  react_frontend/src/components/emperf/Ps_1_2_Fp.js
  react_frontend/src/components/emperf/perflook/Psq_Fp.js
  react_frontend/src/components/fieldinfo/facility/Adm.js
  react_frontend/src/components/fieldinfo/facility/Fl.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/components/fieldinfo/project/detailSet/Esd.js
  react_frontend/src/components/fieldinfo/project/detailSet/Esd_Fp.js
  react_frontend/src/components/fieldinfo/project/detailSet/Fd.js
  react_frontend/src/components/fieldinfo/project/detailSet/Pd.js
  react_frontend/src/components/fieldinfo/project/detailSet/Rm.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/modals/PdModal.js
Labels: 버그, 프론트엔드, 기능생성

#179 [Fix] 사용금액 버그 해결
  react_frontend/src/TableCustom.js
  react_frontend/src/components/emperf/Ps_1_2.js
Labels: 버그, 프론트엔드

#180 [Fix] 이전 PR 수정사항 반영
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/components/fieldinfo/facility/Adm.js
  react_frontend/src/components/fieldinfo/facility/Fl.js
Labels: 버그, 프론트엔드

#181 [Fix] 수정 사항 반영
  react_frontend/src/ChartCustom.js
  react_frontend/src/FormItem/DropDown.js
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/components/analfc/Eqf.js
Labels: 프론트엔드, 스타일

#182 [Fix] 최종발표 수정사항 반영
  react_frontend/src/FormItem/SelectCalendar.js
  react_frontend/src/SearchForms.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/TabsContainer.js
  react_frontend/src/atoms/searchFormAtoms.js
  react_frontend/src/components/analfc/Ca.js
  react_frontend/src/components/analfc/Sa.js
  react_frontend/src/components/emperf/Ps_1_2.js
  react_frontend/src/components/emperf/Ps_1_2_Fp.js
  react_frontend/src/components/emperf/perflook/Psq.js
  react_frontend/src/components/emperf/perflook/Psq_Fp.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/components/fieldinfo/project/detailSet/Esd_Fp.js
  react_frontend/src/components/fieldinfo/project/detailSet/Rm.js
  react_frontend/src/components/sysmng/Cm.js
Labels: 버그, 프론트엔드, 기능생성

#183 [Feat] 챗봇 UI 생성
  react_frontend/src/Chat.js
  react_frontend/src/assets/json/tableColumn.js
  react_frontend/src/chat/Chatting.js
  react_frontend/src/chat/UserList.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성
