Repository POS-CO2/2024_PGMS_FE, pull requests merged in 2024-09, with the labels that each got.

#125 [Feat] 증빙자료 모달 관련 기능, 엑셀 다운로드 구현
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/css/sdModal.css
  react_frontend/src/assets/json/sd.js
  react_frontend/src/assets/json/tableColumn.js
  react_frontend/src/components/emperf/Ps_1_2.js
  react_frontend/src/components/emperf/perflook/Psq.js
  react_frontend/src/components/emperf/perflook/Tep.js
  react_frontend/src/components/fieldinfo/emission/Esm.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#126 [Style] 기본 레이아웃 스타일 수정
  react_frontend/package-lock.json
  react_frontend/package.json
  react_frontend/src/AppContainer.js
  react_frontend/src/Button.js
  react_frontend/src/Footer.js
  react_frontend/src/FormItem/SearchAtModal.js
  react_frontend/src/FormItem/SearchBtn.js
  react_frontend/src/Header.js
  react_frontend/src/Language.js
  react_frontend/src/Main.js
  react_frontend/src/Menu.js
  react_frontend/src/MenuGrid.js
  react_frontend/src/MenuList.js
  react_frontend/src/Navigation.js
  react_frontend/src/Sidebar.js
  react_frontend/src/SiteLayout.js
  react_frontend/src/Tab.js
  react_frontend/src/Tabbar.js
  react_frontend/src/Table.js
  react_frontend/src/TabsContainer.js
  react_frontend/src/Title.js
  react_frontend/src/assets/css/app.css
  react_frontend/src/assets/css/favorite.css
  react_frontend/src/assets/css/footer.css
  react_frontend/src/assets/css/header.css
  react_frontend/src/assets/css/main.css
  react_frontend/src/assets/css/menu.css
  react_frontend/src/assets/css/navbar.css
  react_frontend/src/assets/css/navigation.css
  react_frontend/src/assets/css/pdModal.css
  react_frontend/src/assets/css/pjtModal.css
  react_frontend/src/assets/css/rmModal.css
  react_frontend/src/assets/logo.svg
  react_frontend/src/components/fieldinfo/facility/Fm.js
Labels: 프론트엔드, 스타일

#127 [Feat] 활동량 관리 - 더블클릭 수정, 엑셀양식 다운로드
  react_frontend/package-lock.json
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/css/ps12.css
  react_frontend/src/assets/json/tableColumn.js
  react_frontend/src/components/emperf/Ps_1_2.js
  react_frontend/src/components/fieldinfo/project/Rm.js
Labels: 프론트엔드, 기능생성

#128 [HotFix] 탭 로컬스토리지에 저장
  react_frontend/src/TabsContainer.js
Labels: 버그, 프론트엔드

#129 [HotFix] 홈 탭 activeTab 에 저장안되는 이슈 해결
  react_frontend/src/SiteLayout.js
  react_frontend/src/TabsContainer.js
Labels: 버그

#131 [HotFix] Tab Css 수정
  react_frontend/src/TabsContainer.js
Labels: 버그, 프론트엔드, 스타일

#134 [Feat] 모달 필수 입력값 검증
  react_frontend/package-lock.json
  react_frontend/src/SearchForms.js
  react_frontend/src/assets/css/pdModal.css
  react_frontend/src/assets/css/ps12UploadExcelModal.css
  react_frontend/src/assets/css/sdModal.css
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#135 [Fix] 메뉴관리 페이지 버그 픽스
  react_frontend/src/Table.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Mm.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/modals/PdModal.js
Labels: 버그, 프론트엔드

#136 [Refator] 프로젝트 상세설정 페이지로 통합(담당자지정, 설비지정, 매출액관리)
  react_frontend/TableCustom
  react_frontend/package-lock.json
  react_frontend/package.json
  react_frontend/public/index.html
  react_frontend/src/App.js
  react_frontend/src/Button.js
  react_frontend/src/FormItem/SearchProjectModal.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/TabsContainer.js
  react_frontend/src/actions/commonActions.js
  react_frontend/src/assets/css/main.css
  react_frontend/src/assets/css/newTable.css
  react_frontend/src/assets/css/pds.css
  react_frontend/src/assets/css/pjtModal.css
  react_frontend/src/assets/json/tableColumn.js
  react_frontend/src/atoms/pdsAtoms.js
  react_frontend/src/components/fieldinfo/facility/Fad.js
  react_frontend/src/components/fieldinfo/facility/Fm.js
  react_frontend/src/components/fieldinfo/project/Pd.js
  react_frontend/src/components/fieldinfo/project/detailSet/Esd.js
  react_frontend/src/components/fieldinfo/project/detailSet/Fd.js
  react_frontend/src/components/fieldinfo/project/detailSet/Pd.js
  react_frontend/src/components/fieldinfo/project/detailSet/Pdc.js
  react_frontend/src/components/fieldinfo/project/detailSet/PdsStateMgr.js
  react_frontend/src/components/fieldinfo/project/detailSet/Rm.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드

#138 [Refactor] 설비관리 화면 합치기(설비LIB관리, 활동자료 목록)
  react_frontend/src/FormItem/DropDown.js
  react_frontend/src/FormItem/InputText.js
  react_frontend/src/FormItem/SearchProjectModal.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/css/pds.css
  react_frontend/src/assets/css/pjtModal.css
  react_frontend/src/components/fieldinfo/Efm.js
  react_frontend/src/components/fieldinfo/facility/Fam.js
  react_frontend/src/components/fieldinfo/facility/Fl.js
  react_frontend/src/components/fieldinfo/project/detailSet/Pd.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드

#139 [Fix] onProjectSelect 속성 추가
  react_frontend/src/FormItem/DropDown.js
Labels: 버그

#140 [Style] 모든 컴포넌트 폰트 적용
  react_frontend/src/Chart.js
  react_frontend/src/FormItem/DropDown.js
  react_frontend/src/FormItem/SearchAtModal.js
  react_frontend/src/FormItem/SearchProjectModal.js
  react_frontend/src/FormItem/SelectCalendar.js
  react_frontend/src/Language.js
  react_frontend/src/Main.js
  react_frontend/src/Main_Hp.js
  react_frontend/src/SearchForms.js
  react_frontend/src/Sidebar.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/TabsContainer.js
  react_frontend/src/assets/css/main.css
  react_frontend/src/assets/css/pjtModal.css
  react_frontend/src/components/fieldinfo/Efm.js
  react_frontend/src/index.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 스타일

#141 [Style] 버튼 스타일 변경
  react_frontend/src/App.js
  react_frontend/src/Button.js
  react_frontend/src/FormItem/SearchAtModal.js
  react_frontend/src/FormItem/SearchBtn.js
  react_frontend/src/FormItem/SearchProjectModal.js
  react_frontend/src/SearchForms.js
  react_frontend/src/SiteLayout.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/css/formItem.css
  react_frontend/src/assets/css/newTable.css
  react_frontend/src/assets/css/pds.css
  react_frontend/src/assets/css/pjtModal.css
  react_frontend/src/components/emperf/Ps_1_2.js
  react_frontend/src/components/emperf/Ps_1_2_Fp.js
  react_frontend/src/components/fieldinfo/facility/Adm.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/components/fieldinfo/project/Rm.js
  react_frontend/src/components/fieldinfo/project/detailSet/Fd.js
  react_frontend/src/components/fieldinfo/project/detailSet/Pd.js
  react_frontend/src/components/fieldinfo/project/detailSet/Pdc.js
  react_frontend/src/components/fieldinfo/project/detailSet/Pds.js
  react_frontend/src/components/fieldinfo/project/detailSet/PdsStateMgr.js
  react_frontend/src/components/fieldinfo/project/detailSet/Rm.js
  react_frontend/src/components/sysmng/Mm.js
  react_frontend/src/modals/PdModal.js
Labels: 스타일

#143 [Feat] 활동량 관리 - 멘토 피드백 반영
  react_frontend/src/FormItem/DropDown.js
  react_frontend/src/FormItem/SearchAtModal.js
  react_frontend/src/assets/css/formItem.css
  react_frontend/src/assets/css/searchForm.css
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/components/emperf/Ps_1_2.js
  react_frontend/src/components/emperf/Ps_1_2_Fp.js
  react_frontend/src/components/emperf/perflook/Psq.js
  react_frontend/src/components/emperf/perflook/Psq_Fp.js
Labels: 버그, 프론트엔드, 기능생성, 스타일

#144 [Refactor] 시스템 관리 페이지 피드백 반영
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/css/sysmng.css
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Mm.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성, 스타일

#145 [Refactor] 프로젝트 기능 관련 수정 요구사항 반영 완료
  react_frontend/src/Button.js
  react_frontend/src/FormItem/SearchProjectModal.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/actions/commonActions.js
  react_frontend/src/assets/css/pds.css
  react_frontend/src/atoms/pdsAtoms.js
  react_frontend/src/components/fieldinfo/facility/Adm.js
  react_frontend/src/components/fieldinfo/facility/Fad.js
  react_frontend/src/components/fieldinfo/facility/Fl.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/components/fieldinfo/project/detailSet/Esd.js
  react_frontend/src/components/fieldinfo/project/detailSet/Fd.js
  react_frontend/src/components/fieldinfo/project/detailSet/Pd.js
  react_frontend/src/components/fieldinfo/project/detailSet/Pds.js
  react_frontend/src/components/fieldinfo/project/detailSet/PdsStateMgr.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Mal.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 스타일

#146 [Feat] 프로젝트별 조회 - 멘토 피드백 반영
  react_frontend/package-lock.json
  react_frontend/package.json
  react_frontend/src/FormItem/SearchAtModal.js
  react_frontend/src/SearchForms.js
  react_frontend/src/assets/css/formItem.css
  react_frontend/src/assets/css/psq.css
  react_frontend/src/assets/json/tableColumn.js
  react_frontend/src/components/emperf/Ps_1_2.js
  react_frontend/src/components/emperf/Ps_1_2_Fp.js
  react_frontend/src/components/emperf/perflook/Psq.js
  react_frontend/src/components/emperf/perflook/Psq_Fp.js
  react_frontend/src/components/fieldinfo/emission/Esm.js
  react_frontend/src/components/fieldinfo/emission/Esm_Fp.js
  react_frontend/src/utils/AxiosInstance.js
Labels: 프론트엔드, 기능생성

#147 [Feat] 채팅 기능 구현
  react_frontend/package-lock.json
  react_frontend/package.json
  react_frontend/src/Chat.js
  react_frontend/src/SiteLayout.js
  react_frontend/src/assets/css/chat.css
  react_frontend/src/chat/ChatList.js
  react_frontend/src/chat/Chatting.js
  react_frontend/src/chat/UserList.js
  react_frontend/src/customhook/useWebSocket.js
Labels: 프론트엔드, 기능생성

#148 [Feat] 탭 상태관리, 즐겨찾기 기능 api 연동
  react_frontend/src/App.js
  react_frontend/src/Favorite.js
  react_frontend/src/FormItem/SearchAtModal.js
  react_frontend/src/SearchForms.js
  react_frontend/src/Sidebar.js
  react_frontend/src/SiteLayout.js
  react_frontend/src/Table.js
  react_frontend/src/TabsContainer.js
  react_frontend/src/actions/commonActions.js
  react_frontend/src/assets/css/favorite.css
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/atoms/buttonAtoms.js
  react_frontend/src/atoms/pdsAtoms.js
  react_frontend/src/atoms/searchFormAtoms.js
  react_frontend/src/atoms/tabAtoms.js
  react_frontend/src/basic_modal/modal.css
  react_frontend/src/basic_modal/modal.js
  react_frontend/src/components/emperf/Pmg.js
  react_frontend/src/components/emperf/Ps_1_2.js
  react_frontend/src/components/emperf/perflook/Psq.js
  react_frontend/src/components/emperf/perflook/Tep.js
  react_frontend/src/components/fieldinfo/Efm.js
  react_frontend/src/components/fieldinfo/emission/Esm.js
  react_frontend/src/components/fieldinfo/facility/Adm.js
  react_frontend/src/components/fieldinfo/facility/Fad.js
  react_frontend/src/components/fieldinfo/facility/Fl.js
  react_frontend/src/components/fieldinfo/facility/Fm.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/components/fieldinfo/project/detailSet/Esd.js
  react_frontend/src/components/fieldinfo/project/detailSet/Pds.js
  react_frontend/src/components/fieldinfo/project/detailSet/PdsStateMgr.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Mal.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/index.js
  react_frontend/src/modals/PdModal.js
Labels: 버그, 프론트엔드, 기능생성

#151 [Remove] 불필요한 파일 삭제
  react_frontend/TableCustom
  react_frontend/src/App.js
  react_frontend/src/FormItem/SearchAtModal.js
  react_frontend/src/FormItem/SearchLibModal.js
  react_frontend/src/assets/Polygon 1.svg
  react_frontend/src/assets/json/ems.js
  react_frontend/src/assets/json/manager.js
  react_frontend/src/assets/json/project.js
  react_frontend/src/assets/json/sd.js
  react_frontend/src/assets/json/selectedPjt.js
  react_frontend/src/assets/json/tep.js
  react_frontend/src/components/fieldinfo/emission/Esm.js
  react_frontend/src/components/fieldinfo/emission/Sd.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Mal.js
  react_frontend/src/components/sysmng/Mm.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드

#152 [HotFix] App.js undefined 이슈 해결
  react_frontend/src/App.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/TabsContainer.js
  react_frontend/src/atoms/buttonAtoms.js
  react_frontend/src/atoms/localStorageEffect.js
  react_frontend/src/atoms/pdsAtoms.js
  react_frontend/src/atoms/searchFormAtoms.js
  react_frontend/src/atoms/selectedRowAtoms.js
  react_frontend/src/components/fieldinfo/facility/Adm.js
  react_frontend/src/components/fieldinfo/facility/Fl.js
  react_frontend/src/components/fieldinfo/project/detailSet/Fd.js
  react_frontend/src/modals/PdModal.js
Labels: 버그

#153 [Feat] 메뉴명에 *로 권한 표시, 아이콘 수정
  react_frontend/src/App.js
  react_frontend/src/Button.js
  react_frontend/src/FormItem/SearchBtn.js
  react_frontend/src/SearchForms.js
  react_frontend/src/Sidebar.js
  react_frontend/src/SiteLayout.js
  react_frontend/src/atoms/searchFormAtoms.js
  react_frontend/src/components/emperf/Ps_1_2.js
  react_frontend/src/components/emperf/Ps_1_2_Fp.js
  react_frontend/src/components/emperf/perflook/Psq_Fp.js
  react_frontend/src/components/emperf/perflook/Tep.js
  react_frontend/src/components/fieldinfo/emission/Esm_Fp.js
  react_frontend/src/components/fieldinfo/facility/Fl.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/components/fieldinfo/project/detailSet/Esd_Fp.js
  react_frontend/src/components/fieldinfo/project/detailSet/Pds.js
  react_frontend/src/components/fieldinfo/project/detailSet/PdsStateMgr.js
Labels: 프론트엔드, 기능생성

#154 [Feat] 분석 화면들 구현
  react_frontend/package-lock.json
  react_frontend/src/FormItem/SearchBtn.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/css/chart.css
  react_frontend/src/assets/css/newTable.css
  react_frontend/src/assets/css/ps12UploadExcelModal.css
  react_frontend/src/assets/css/sdModal.css
  react_frontend/src/assets/json/saDataEx.js
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/assets/json/tableColumn.js
  react_frontend/src/components/analfc/Ca.js
  react_frontend/src/components/analfc/Ea.js
  react_frontend/src/components/analfc/Sa.js
  react_frontend/src/components/emperf/perflook/Tep.js
  react_frontend/src/components/fieldinfo/project/detailSet/Esd.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#155 [Feat] 등록/수정 시 새로고침 기능 구현
  react_frontend/src/ChartCustom.js
  react_frontend/src/SearchForms.js
  react_frontend/src/SiteLayout.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/TabsContainer.js
  react_frontend/src/actions/commonActions.js
  react_frontend/src/assets/css/newTable.css
  react_frontend/src/assets/css/pds.css
  react_frontend/src/assets/css/pjtModal.css
  react_frontend/src/atoms/pdsAtoms.js
  react_frontend/src/atoms/searchFormAtoms.js
  react_frontend/src/atoms/selectedRowAtoms.js
  react_frontend/src/components/analfc/Ca.js
  react_frontend/src/components/analfc/Ea.js
  react_frontend/src/components/analfc/Sa.js
  react_frontend/src/components/emperf/Ps_1_2.js
  react_frontend/src/components/emperf/perflook/Psq.js
  react_frontend/src/components/emperf/perflook/Psq_Fp.js
  react_frontend/src/components/emperf/perflook/Tep.js
  react_frontend/src/components/fieldinfo/facility/Adm.js
  react_frontend/src/components/fieldinfo/facility/Fl.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/components/fieldinfo/project/detailSet/Esd.js
  react_frontend/src/components/fieldinfo/project/detailSet/Fd.js
  react_frontend/src/components/fieldinfo/project/detailSet/Pd.js
  react_frontend/src/components/fieldinfo/project/detailSet/PdsStateMgr.js
  react_frontend/src/components/fieldinfo/project/detailSet/Rm.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Mal.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#156 [Fix] 총량실적 오류 해결
  react_frontend/src/Sidebar.js
  react_frontend/src/SiteLayout.js
  react_frontend/src/TabsContainer.js
  react_frontend/src/atoms/searchFormAtoms.js
  react_frontend/src/atoms/tabAtoms.js
  react_frontend/src/components/analfc/Sa.js
  react_frontend/src/components/emperf/perflook/Tep.js
Labels: 프론트엔드, 기능생성

#158 [Refactor] 관리자 대쉬보드 및 메뉴 등 멘토님 피드백 수정사항 반영
  react_frontend/src/Language.js
  react_frontend/src/Main.js
  react_frontend/src/Main_Admin.js
  react_frontend/src/Main_Hp.js
  react_frontend/src/SiteLayout.js
  react_frontend/src/TabsContainer.js
  react_frontend/src/assets/css/grid.css
  react_frontend/src/assets/css/gridAdmin.css
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/assets/json/tableColumn.js
  react_frontend/src/components/fieldinfo/facility/Adm.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Mm.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/modals/PdModal.js
  react_frontend/src/utils/AxiosInstance.js
Labels: 버그, 프론트엔드, 기능생성, 스타일

#159 [Feat] 필수값 *표시
  react_frontend/src/assets/css/pdModal.css
  react_frontend/src/assets/css/rmModal.css
  react_frontend/src/assets/css/sysmng.css
  react_frontend/src/components/sysmng/Mm.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 스타일

#160 [Fix] 시스템 관리자 메뉴 및 메인보드 무한루프 제거
  react_frontend/src/Main_Admin.js
  react_frontend/src/Table.js
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/assets/json/tableColumn.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Mal.js
  react_frontend/src/components/sysmng/Mm.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/modals/PdModal.js
Labels: 버그, 프론트엔드

#162 [Refactor] 본사담당자 메인보드 배출량 및 활동량으로 수정
  react_frontend/src/Main_Hp.js
  react_frontend/src/assets/css/gridHp.css
  react_frontend/src/components/fieldinfo/facility/Adm.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#161 [Feat] 공지사항 기능 구현
  react_frontend/src/Chat.js
  react_frontend/src/chat/ChatList.js
  react_frontend/src/chat/Chatting.js
  react_frontend/src/chat/UserList.js
Labels: 프론트엔드, 기능생성

#163 [Refactor] 멘토링 요구사항 반영(테이블 컴포넌트 제외)
  react_frontend/src/App.js
  react_frontend/src/Button.js
  react_frontend/src/ChartCustom.js
  react_frontend/src/Favorite.js
  react_frontend/src/FormItem/InputText.js
  react_frontend/src/FormItem/SearchAtModal.js
  react_frontend/src/FormItem/SearchBtn.js
  react_frontend/src/Main_Admin.js
  react_frontend/src/Main_Hp.js
  react_frontend/src/SearchForms.js
  react_frontend/src/Sidebar.js
  react_frontend/src/SiteLayout.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/TabsContainer.js
  react_frontend/src/assets/css/pds.css
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/assets/json/tableColumn.js
  react_frontend/src/atoms/buttonAtoms.js
  react_frontend/src/atoms/pdsAtoms.js
  react_frontend/src/atoms/searchFormAtoms.js
  react_frontend/src/atoms/selectedRowAtoms.js
  react_frontend/src/atoms/tabAtoms.js
  react_frontend/src/components/analfc/Ca.js
  react_frontend/src/components/analfc/Ea.js
  react_frontend/src/components/analfc/Sa.js
  react_frontend/src/components/emperf/Ps_1_2.js
  react_frontend/src/components/emperf/Ps_1_2_Fp.js
  react_frontend/src/components/emperf/perflook/Psq.js
  react_frontend/src/components/emperf/perflook/Psq_Fp.js
  react_frontend/src/components/emperf/perflook/Tep.js
  react_frontend/src/components/fieldinfo/facility/Adm.js
  react_frontend/src/components/fieldinfo/facility/Fl.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/components/fieldinfo/project/detailSet/Esd.js
  react_frontend/src/components/fieldinfo/project/detailSet/Esd_Fp.js
  react_frontend/src/components/fieldinfo/project/detailSet/Fd.js
  react_frontend/src/components/fieldinfo/project/detailSet/Pd.js
  react_frontend/src/components/fieldinfo/project/detailSet/Pds.js
  react_frontend/src/components/fieldinfo/project/detailSet/PdsStateMgr.js
  react_frontend/src/components/fieldinfo/project/detailSet/Rm.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Mal.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/modals/PdModal.js
Labels: 버그, 프론트엔드, 기능생성

#164 [Feat] 공지사항 읽음 버튼 및 기능 구현
  react_frontend/src/chat/Chatting.js
Labels: 프론트엔드, 기능생성
