Repository POS-CO2/2024_PGMS_FE, pull requests merged in 2024-08, with the labels that each got.

#28 [Feat] 즐겨찾기 기능 구현
  react_frontend/src/AppContainer.js
  react_frontend/src/Favorite.js
  react_frontend/src/SiteLayout.js
  react_frontend/src/Tabbar.js
  react_frontend/src/assets/css/favorite.css
  react_frontend/src/components/Mal.js
Labels: 프론트엔드, 기능생성

#30 [Hotfix] 메뉴 구조 변경
  react_frontend/src/App.js
  react_frontend/src/SiteLayout.js
  react_frontend/src/Tabbar.js
  react_frontend/src/components/emperf/Pmg.js
  react_frontend/src/components/emperf/Ps_1_2.js
  react_frontend/src/components/emperf/perflook/Psq.js
  react_frontend/src/components/emperf/perflook/Tep.js
  react_frontend/src/components/fieldinfo/Efm.js
  react_frontend/src/components/fieldinfo/emission/Esm.js
  react_frontend/src/components/fieldinfo/emission/Sd.js
  react_frontend/src/components/fieldinfo/facility/Fad.js
  react_frontend/src/components/fieldinfo/facility/Fam.js
  react_frontend/src/components/fieldinfo/facility/Fl.js
  react_frontend/src/components/fieldinfo/facility/Fm.js
  react_frontend/src/components/fieldinfo/project/Pd.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/components/fieldinfo/project/Rm.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Mal.js
  react_frontend/src/components/sysmng/Mm.js
  react_frontend/src/components/sysmng/Um.js
Labels: 버그, 프론트엔드

#33 [Feat] Mui & Antd 추가 및 네비게이션바 수정
  react_frontend/package-lock.json
  react_frontend/package.json
  react_frontend/public/index.html
  react_frontend/src/AppContainer.js
  react_frontend/src/Header.js
  react_frontend/src/SiteLayout.js
  react_frontend/src/assets/css/app.css
  react_frontend/src/assets/css/layer.css
  react_frontend/src/assets/css/main.css
  react_frontend/src/assets/css/navbar.css
  react_frontend/src/assets/css/navigation.css
  react_frontend/src/assets/css/table.css
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Mm.js
Labels: 버그, 프론트엔드, 기능생성

#34 Feature/table
  react_frontend/config/webpack.config.js
  react_frontend/src/App.js
  react_frontend/src/Table.js
  react_frontend/src/Title.js
  react_frontend/src/assets/css/favorite.css
  react_frontend/src/assets/css/newTable.css
  react_frontend/src/assets/json/manager.js
  react_frontend/src/assets/json/selectedPjt.js
  react_frontend/src/components/fieldinfo/project/Pd.js
  react_frontend/src/test.js
  react_frontend/src/test1.js
Labels: 프론트엔드, 기능생성

#36 [Feat] Login 페이지 구현(#35)
  react_frontend/src/App.js
  react_frontend/src/assets/css/login.css
  react_frontend/src/assets/images/poscoenc.png
  react_frontend/src/components/login/Login.js
Labels: 프론트엔드, 기능생성

#38 [Fix] git conflict
  react_frontend/src/App.js
Labels: 버그, 프론트엔드, 기능생성

#39 [Fix] 이미지 깨짐 현상 수정
  react_frontend/src/Footer.js
  react_frontend/src/assets/css/footer.css
  react_frontend/src/assets/css/login.css
  react_frontend/src/components/login/Login.js
Labels: 버그, 프론트엔드

#40 [Feat] Modal 컴포넌트 분리 및 Input에 값 전달 등 (#31)
  react_frontend/src/FormItem/DropDown.js
  react_frontend/src/FormItem/InputText.js
  react_frontend/src/FormItem/ModalComponent.js
  react_frontend/src/FormItem/SearchAtModal.js
  react_frontend/src/FormItem/SearchBtn.js
  react_frontend/src/FormItem/SearchLibModal.js
  react_frontend/src/FormItem/SearchProjectModal.js
  react_frontend/src/FormItem/SelectCalendar.js
  react_frontend/src/SearchForm/SearchFormEx.js
  react_frontend/src/assets/css/formItem.css
  react_frontend/src/assets/css/searchForm.css
  react_frontend/src/components/emperf/Ps_1_2.js
Labels: 프론트엔드, 기능생성

#50 [Fix] user 로그인 및 로그아웃 구현
  react_frontend/public/index.html
  react_frontend/src/App.js
  react_frontend/src/AppContainer.js
  react_frontend/src/Header.js
  react_frontend/src/SiteLayout.js
  react_frontend/src/assets/css/header.css
  react_frontend/src/assets/css/main.css
  react_frontend/src/assets/css/table.css
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/utils/Api.js
  react_frontend/src/utils/AxiosInstance.js
Labels: 프론트엔드, 기능생성

#51 [Refactor] SearchForm 공통 컴포넌트화 구현
  react_frontend/src/SearchForms.js
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/components/emperf/Ps_1_2.js
Labels: 프론트엔드, 기능생성

#54 [Feat] 메뉴 관리 기능 구현
  react_frontend/package-lock.json
  react_frontend/package.json
  react_frontend/src/App.js
  react_frontend/src/AppContainer.js
  react_frontend/src/SearchForms.js
  react_frontend/src/SiteLayout.js
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/components/login/Login.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Mm.js
  react_frontend/src/components/sysmng/Um.js
Labels: 프론트엔드, 기능생성

#56 [Feat] 시스템 관리 화면 구성
  react_frontend/src/Main.js
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/assets/json/selectedPjt.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Um.js
Labels: 프론트엔드, 기능생성

#58 [Feat] 프로젝트 찾기 모달 구현 (#57)
  react_frontend/src/FormItem/SearchAtModal.js
  react_frontend/src/FormItem/SearchProjectModal.js
  react_frontend/src/SearchForms.js
  react_frontend/src/assets/css/formItem.css
  react_frontend/src/assets/css/pjtModal.css
  react_frontend/src/assets/json/project.js
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/components/fieldinfo/project/Pd.js
Labels: 프론트엔드, 기능생성

#61 [Feat] 프로젝트 찾기 모달 구현 완료
  react_frontend/src/Button.js
  react_frontend/src/FormItem/SearchAtModal.js
  react_frontend/src/FormItem/SearchProjectModal.js
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/css/pdModal.css
  react_frontend/src/assets/json/manager.js
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/assets/json/selectedPjt.js
  react_frontend/src/basic_modal/modal.js
  react_frontend/src/components/fieldinfo/project/Pd.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#65 [Feat] 기본 화면 구현 (#64)
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/assets/json/selectedPjt.js
  react_frontend/src/components/fieldinfo/facility/Fad.js
  react_frontend/src/components/fieldinfo/facility/Fam.js
  react_frontend/src/components/fieldinfo/facility/Fl.js
  react_frontend/src/components/fieldinfo/project/Pd.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/components/fieldinfo/project/Rm.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#70 [Feat] 설비 LIB 관리 화면 구현 (#20)
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/components/fieldinfo/facility/Fl.js
  react_frontend/src/components/fieldinfo/project/Pd.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#71 [Feat] 수정 버튼 기능 구현
  react_frontend/package-lock.json
  react_frontend/package.json
  react_frontend/src/Button.js
  react_frontend/src/FormItem/SearchProjectModal.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/json/selectedPjt.js
  react_frontend/src/components/fieldinfo/facility/Fad.js
  react_frontend/src/components/fieldinfo/facility/Fam.js
  react_frontend/src/components/fieldinfo/facility/Fl.js
  react_frontend/src/components/fieldinfo/project/Pd.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/components/fieldinfo/project/Rm.js
Labels: 프론트엔드, 기능생성

#73 [Refactor] 테이블 row 클릭시 데이터전달 로직 수정
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/components/fieldinfo/facility/Fam.js
  react_frontend/src/components/fieldinfo/facility/Fl.js
  react_frontend/src/components/fieldinfo/project/Pd.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/components/fieldinfo/project/Rm.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#76 [Feat] 활동 자료 관리 화면 구현 (#18)
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/components/fieldinfo/facility/Fam.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#77 [Feat] 시스템관리 수정사항 반영 & 메인 대쉬보드 수정
  react_frontend/public/index.html
  react_frontend/src/Chart.js
  react_frontend/src/Header.js
  react_frontend/src/Main.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/css/favorite.css
  react_frontend/src/assets/css/grid.css
  react_frontend/src/assets/css/main.css
  react_frontend/src/assets/css/pdModal.css
  react_frontend/src/assets/json/chartData.js
  react_frontend/src/assets/json/data.js
  react_frontend/src/assets/json/selectedPjt.js
  react_frontend/src/components/fieldinfo/facility/Fm.js
  react_frontend/src/components/login/Login.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Mm.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#78 [Fix] 공통 컴포넌트에 특정 기능의 칼럼명을 사용하여 수정
  react_frontend/src/TableCustom.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/modals/PdModal.js
Labels: 버그

#80 [Feat] 설비 LIB 관리 수정 버튼 Double Click에서 모달로 변경
  react_frontend/src/TableCustom.js
  react_frontend/src/components/fieldinfo/facility/Fl.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#79 [Feat] Navigation Fold 기능 구현
  react_frontend/src/Navigation.js
  react_frontend/src/assets/css/navigation.css
Labels: 프론트엔드, 기능생성

#82 [Fix] sysmng.css 중복 정의 에러 해결
  react_frontend/src/modals/PdModal.js
Labels: 버그

#83 [Fix] PgAddModal is undefined 에러 해결
  react_frontend/src/TableCustom.js
Labels: 버그

#85 [Fix] Logout 컴포넌트 수정
  react_frontend/src/Header.js
  react_frontend/src/assets/css/header.css
  react_frontend/src/modals/PdModal.js
Labels: 버그, 프론트엔드

#86 [Refactor] 차트 라이브러리 변경 및 recharts 라이브러리 제거
  react_frontend/package-lock.json
  react_frontend/package.json
  react_frontend/src/ChartCustom.js
  react_frontend/src/components/emperf/perflook/Psq.js
  react_frontend/src/components/emperf/perflook/Tep.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드

#87 [Feat] 현장담당자(fm) 화면 구현
  react_frontend/package-lock.json
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/components/emperf/Ps_1_2_fm.js
  react_frontend/src/components/emperf/perflook/Psq_fm.js
  react_frontend/src/components/fieldinfo/emission/Esm_fm.js
Labels: 프론트엔드, 기능생성

#88 [Feat] 시스템구현 & 배출계수 관리 & 설비 지정 css 수정 및 테이블, 버튼, 모달 색상 수정
  react_frontend/src/Button.js
  react_frontend/src/Main.js
  react_frontend/src/Table.js
  react_frontend/src/assets/css/grid.css
  react_frontend/src/assets/css/pdModal.css
  react_frontend/src/assets/css/pjtModal.css
  react_frontend/src/assets/css/sysmng.css
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/assets/json/selectedPjt.js
  react_frontend/src/components/fieldinfo/Efm.js
  react_frontend/src/components/fieldinfo/facility/Fm.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#89 네비게이션 호버 및 현재 위치 표시 기능 생성
  react_frontend/src/Menu.js
  react_frontend/src/MenuList.js
  react_frontend/src/Navigation.js
  react_frontend/src/SiteLayout.js
  react_frontend/src/assets/css/menu.css
Labels: 프론트엔드, 기능생성

#90 [Style] css 수정 및 추가
  react_frontend/src/Button.js
  react_frontend/src/FormItem/DropDown.js
  react_frontend/src/FormItem/SearchBtn.js
  react_frontend/src/InnerTabs.js
  react_frontend/src/assets/css/esm.css
  react_frontend/src/assets/css/formItem.css
  react_frontend/src/assets/css/innerTabs.css
  react_frontend/src/assets/css/ps12.css
  react_frontend/src/assets/css/ps12UploadExcelModal.css
  react_frontend/src/assets/css/searchForm.css
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/components/emperf/Ps_1_2.js
  react_frontend/src/components/emperf/perflook/Psq.js
  react_frontend/src/components/emperf/perflook/Tep.js
  react_frontend/src/components/fieldinfo/emission/Esm.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드

#92 [Feat] 삭제 버튼 데이터 전달
  react_frontend/package-lock.json
  react_frontend/package.json
  react_frontend/src/components/fieldinfo/project/Pd.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#91 [Feat] 활동자료 지정 화면 구현
  react_frontend/src/FormItem/SearchAtModal.js
  react_frontend/src/FormItem/SearchLibModal.js
  react_frontend/src/FormItem/SearchProjectModal.js
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/css/pjtModal.css
  react_frontend/src/assets/json/selectedPjt.js
  react_frontend/src/components/fieldinfo/facility/Fad.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#93 [Feat] 설비 지정 & 프로젝트 찾기 모달 백엔드 연동
  react_frontend/package-lock.json
  react_frontend/src/App.js
  react_frontend/src/FormItem/SearchAtModal.js
  react_frontend/src/FormItem/SearchProjectModal.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/components/fieldinfo/Efm.js
  react_frontend/src/components/fieldinfo/facility/Fm.js
  react_frontend/src/modals/PdModal.js
  react_frontend/src/utils/AxiosInstance.js
Labels: 프론트엔드, 기능생성

#97 [Feat] 담당자 지정 api 연동
  react_frontend/src/FormItem/SearchProjectModal.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/components/fieldinfo/project/Pd.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#98 [Feat] 시스템관리 및 배출계수 지정 & 설비 지정 백엔드 연동 (메뉴관리 제외)
  react_frontend/src/FormItem/DropDown.js
  react_frontend/src/Menu.js
  react_frontend/src/Navigation.js
  react_frontend/src/SiteLayout.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/components/fieldinfo/Efm.js
  react_frontend/src/components/fieldinfo/facility/Fm.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Mal.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/modals/PdModal.js
  react_frontend/src/utils/AxiosInstance.js
Labels: 프론트엔드, 기능생성

#100 [Feat] 매출액 관리 api 연동
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/css/rmModal.css
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/components/fieldinfo/project/Pd.js
  react_frontend/src/components/fieldinfo/project/Rm.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#101 [Feat] 프로젝트 관리 api 연동
  react_frontend/src/FormItem/SearchProjectModal.js
  react_frontend/src/assets/css/rmModal.css
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#102 [Style] 컬럼명 한글로 변경
  react_frontend/package-lock.json
  react_frontend/package.json
  react_frontend/src/FormItem/SearchAtModal.js
  react_frontend/src/FormItem/SearchProjectModal.js
  react_frontend/src/FormItem/SelectCalendar.js
  react_frontend/src/Table.js
  react_frontend/src/assets/css/formItem.css
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/components/fieldinfo/project/Pd.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#103 [Feat] 활동량 관리 백엔드 연동
  react_frontend/src/FormItem/DropDown.js
  react_frontend/src/FormItem/SearchAtModal.js
  react_frontend/src/SearchForms.js
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/components/emperf/Ps_1_2.js
Labels: 프론트엔드, 기능생성

#104 [Fix] 대상년도 활성화
  react_frontend/src/components/emperf/Ps_1_2.js
Labels: 버그

#108 [Feat] 메뉴 관리 백엔드 연동 & DeleteModal Sweet Alert 추가
  react_frontend/src/App.js
  react_frontend/src/FormItem/DropDown.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/css/app.css
  react_frontend/src/assets/css/esm.css
  react_frontend/src/assets/css/footer.css
  react_frontend/src/assets/css/menu.css
  react_frontend/src/assets/css/navigation.css
  react_frontend/src/assets/css/sysmng.css
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/components/fieldinfo/facility/Fm.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Mal.js
  react_frontend/src/components/sysmng/Mm.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/modals/PdModal.js
Labels: 버그, 프론트엔드, 기능생성

#109 [Feat] 탭 별 데이터 분리, 프로젝트 선택시 대상년도 초기화
  react_frontend/src/SearchForms.js
  react_frontend/src/components/emperf/Ps_1_2.js
Labels: 프론트엔드, 기능생성

#110 [Feat] 설비 LIB 관리 api 연동 (#106)
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/css/rmModal.css
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/components/fieldinfo/facility/Fl.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/components/fieldinfo/project/Rm.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#111 [Feat] 메뉴 관리 수정 및 수정 시 반영 및 전체 Css 수정
  react_frontend/src/App.js
  react_frontend/src/assets/css/sysmng.css
  react_frontend/src/components/fieldinfo/Efm.js
  react_frontend/src/components/fieldinfo/facility/Fm.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Mal.js
  react_frontend/src/components/sysmng/Mm.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/modals/PdModal.js
Labels: 버그, 프론트엔드, 기능생성

#112 [Feat] 활동자료 관리 api 연동 (#107)
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/components/fieldinfo/facility/Fam.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#113 [Feat] 테이블 칼럼 hidden 및 한글화 처리 통합
  react_frontend/package-lock.json
  react_frontend/package.json
  react_frontend/src/FormItem/SearchAtModal.js
  react_frontend/src/FormItem/SearchProjectModal.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/json/tableColumn.js
  react_frontend/src/components/fieldinfo/Efm.js
  react_frontend/src/components/fieldinfo/facility/Fm.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/components/sysmng/Cm.js
  react_frontend/src/components/sysmng/Mal.js
  react_frontend/src/components/sysmng/Mm.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#114 [Feat] 활동자료 지정 api 연동 (#105)
  react_frontend/src/FormItem/SearchAtModal.js
  react_frontend/src/FormItem/SearchLibModal.js
  react_frontend/src/FormItem/SearchProjectModal.js
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/json/tableColumn.js
  react_frontend/src/components/fieldinfo/facility/Fad.js
  react_frontend/src/components/fieldinfo/facility/Fam.js
  react_frontend/src/components/fieldinfo/facility/Fl.js
  react_frontend/src/components/fieldinfo/project/Pd.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/components/fieldinfo/project/Rm.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#115 [Feat] 메뉴 수정 수정 및 모달 테이블 페이지네이션 추가
  react_frontend/src/FormItem/SearchLibModal.js
  react_frontend/src/FormItem/SearchProjectModal.js
  react_frontend/src/Main.js
  react_frontend/src/Menu.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/css/grid.css
  react_frontend/src/assets/css/login.css
  react_frontend/src/assets/images/poscoenc.jpg
  react_frontend/src/components/fieldinfo/facility/Fm.js
  react_frontend/src/components/login/Login.js
  react_frontend/src/components/sysmng/Mm.js
  react_frontend/src/components/sysmng/Um.js
  react_frontend/src/modals/PdModal.js
Labels: 버그, 프론트엔드, 기능생성

#116 [Feat] 총량실적조회, 프로젝트별조회, 배출원관리 백엔드 연동
  react_frontend/src/FormItem/DropDown.js
  react_frontend/src/FormItem/InputText.js
  react_frontend/src/FormItem/InputYear.js
  react_frontend/src/FormItem/SearchAtModal.js
  react_frontend/src/FormItem/SelectCalendar.js
  react_frontend/src/SearchForms.js
  react_frontend/src/assets/css/formItem.css
  react_frontend/src/assets/css/sdModal.css
  react_frontend/src/assets/json/searchFormData.js
  react_frontend/src/assets/json/tableColumn.js
  react_frontend/src/components/emperf/Ps_1_2.js
  react_frontend/src/components/emperf/perflook/Psq.js
  react_frontend/src/components/emperf/perflook/Tep.js
  react_frontend/src/components/fieldinfo/emission/Esm.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성

#117 [Refactor] delete 모달 수정
  react_frontend/src/FormItem/SearchAtModal.js
  react_frontend/src/FormItem/SearchLibModal.js
  react_frontend/src/Table.js
  react_frontend/src/TableCustom.js
  react_frontend/src/assets/css/formItem.css
  react_frontend/src/assets/css/pdModal.css
  react_frontend/src/assets/css/pjtModal.css
  react_frontend/src/assets/css/rmModal.css
  react_frontend/src/components/fieldinfo/facility/Fad.js
  react_frontend/src/components/fieldinfo/facility/Fam.js
  react_frontend/src/components/fieldinfo/facility/Fl.js
  react_frontend/src/components/fieldinfo/project/Pd.js
  react_frontend/src/components/fieldinfo/project/Pg.js
  react_frontend/src/components/fieldinfo/project/Rm.js
  react_frontend/src/modals/PdModal.js
Labels: 프론트엔드, 기능생성
